[project]
name = "dizzy-workspace"
version = "0.1.0"
description = "Dizzy monorepo workspace"
requires-python = ">=3.11"

[tool.uv.workspace]
members = ["pkg/dizzy", "app/*"]

[tool.uv.sources]
dizzy = { workspace = true }

[dependency-groups]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.22",
    "mkdocs-publisher>=1.4.8",
    "mkdocstrings[python]>=0.30.1",
]
