[tool.poetry]
name = "dizzy"
version = "0.1.0"
description = ""
authors = ["Conrad Mearns <conradmearns@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
duckdb = "^1.2.0"
typer = {extras = ["all"], version = "^0.15.1"}
pydantic = "^2.10.6"
fire = "^0.7.0"
python-magic = "^0.4.27"
fsspec = "^2025.2.0"
mypy = "^1.15.0"
pytest = "^8.3.5"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-publisher = "^1.4.6"
mkdocstrings = "^0.28.0"
mkdocstrings-python = "^1.15.0"
mkdocs-gen-files = "^0.5.0"
mkdocs-literate-nav = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
