name: dizzy_dedupe_pulumi
description: A Python program to deploy a Helm chart onto a Kubernetes cluster
runtime:
  name: python
  options:
    toolchain: uv
    virtualenv: .venv
config:
  pulumi:tags:
    value:
      pulumi:template: helm-kubernetes-python
